FROM golang:latest as build

WORKDIR /go/src/yarr
COPY . .

RUN go mod download
RUN CGO_ENABLED=1 go build -tags "sqlite_foreign_keys linux" -ldflags '-linkmode external -extldflags -static -w' -o /go/bin/feedport ./cmd

FROM gcr.io/distroless/static-debian12
COPY --from=build /go/bin/feedport /
CMD ["/yarr"]
